"""Initial tables

Revision ID: 5d9c959d4b04
Revises: 
Create Date: 2026-05-07 21:47:45.123433
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5d9c959d4b04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('response_rate', sa.Integer(), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workos_org_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_workos_org_id'), 'companies', ['workos_org_id'], unique=True)
    op.create_table('developers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('hourly_rate_min', sa.Integer(), nullable=True),
    sa.Column('hourly_rate_max', sa.Integer(), nullable=True),
    sa.Column('daily_rate_min', sa.Integer(), nullable=True),
    sa.Column('daily_rate_max', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('remote_preference', sa.String(length=32), nullable=False),
    sa.Column('languages_spoken', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_years_experience', sa.Integer(), nullable=True),
    sa.Column('seniority', sa.String(length=32), nullable=True),
    sa.Column('domains', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('github_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('resume_url', sa.String(length=512), nullable=True),
    sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('endorsements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('github_linked', sa.Boolean(), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('workos_user_id', sa.String(length=255), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_email'), 'developers', ['email'], unique=True)
    op.create_index(op.f('ix_developers_workos_user_id'), 'developers', ['workos_user_id'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('remote_policy', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('hourly_rate_min', sa.Integer(), nullable=True),
    sa.Column('hourly_rate_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('nice_to_have_skills', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('seniority', sa.String(length=32), nullable=True),
    sa.Column('experience_years_min', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('external', sa.Boolean(), nullable=False),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('application_count', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_slug'), 'jobs', ['slug'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_slug'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_developers_workos_user_id'), table_name='developers')
    op.drop_index(op.f('ix_developers_email'), table_name='developers')
    op.drop_table('developers')
    op.drop_index(op.f('ix_companies_workos_org_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
